name: Compile LaTeX Resume
on:
 push:
   branches:
     - main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout Repository
     uses: actions/checkout@v2
   - name: Set up LaTeX environment
     uses: dante-ev/latex-action@v2
     with:
       root_file: template.tex
   - name: Archive Production Artifacts
     uses: actions/upload-artifact@v2
     with:
       name: template
       path: template.pdf
