name: Compile LaTeX Resume
on:
 push:
   branches: [ main ]
jobs:
 build_latex:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Compile LaTeX document
       uses: xu-cheng/latex-action@v3
       with:
         root_file: template.tex
     - name: Archive production artifacts
       uses: actions/upload-artifact@v2
       with:
         name: resume
         path: resume.pdf
